### ISSUE TITLE
ExtractCandidateMap goes into loop

### ISSUE THREAD

**Issue by maurodragoni** [dbpedia-spotlight/dbpedia-spotlight#138]
Sometimes, the ExtractCandidateMap module enters into a loop and the index.sh script is not able to go ahead and conclude the entire process.
The console output remains freezed at this point:

"INFO 2013-01-30 08:53:47,465 main [ExtractCandidateMap$] -   collecting redirects transitive closure..."

**Comment by sandroacoelho** [comment]
Hi @maurodragoni 

This issue was solved and I have success to create the models in the following languages: german , greek , english, spanish, french , italian, dutch, polish, portuguese and russian.

You have now two options ready to use :

For the statistical backend, please follow these instructions

For Lucene, please follow these

Best,
