### ISSUE TITLE
Demo Server: Returns 406 when "accept:application/xml"

### ISSUE THREAD

**Issue by albifant** [dbpedia-spotlight/dbpedia-spotlight#243]
Hi,

the Demoserver http://spotlight.dbpedia.org/rest/annotate answers with a 406 if you POST to it with "Accept: application/xml" in the header. This is low profile, but it took me a day to figure out the error was not my fault.

Cheers,
Stefan

**Comment by sjuyal** [comment]
Try this:

curl -i -X POST     -H "Accept:text/xml"     -H t-type:application/x-www-form-urlencoded"     -d "disambiguator=Document&confidence=-1&support=-1&text=President%20Obama%20called%20Wednesday%20on%20Congress%20to%20extend%20a%20tax%20break%20for%20students%20included%20in%20last%20year%27s%20economic%20stimulus%20package"        http://spotlight.dbpedia.org/rest/annotate/

As mentioned in the user manual, the following types are supported:
1) text/html
2) application/xhtml+xml
3) text/xml
4) application/json

**Comment by dav009** [comment]
Hi Shashank,

I think something is fishy in your curl, I got an error when I copy&pasted
it into the terminal.

I tried the following and it seems to work:

curl --data
"confidence=-1&disambiguator=Document&support=-1&text=President%20Obama%20called%20Wednesday%20on%20Congress%20to%20extend%20a%20tax%20break%20for%20students%20included%20in%20last%20year%27s%20economic%20stimulus%20package"
-H "Accept: text/xml" "http://spotlight.dbpedia.org/rest/annotate/"

**Comment by sjuyal** [comment]
@dav009 Sorry I forgot to put a double quote ' " ' before 't-type'

This should work fine :)
curl -i -X POST -H "Accept:text/xml" -H "t-type:application/x-www-form-urlencoded" -d "disambiguator=Document&confidence=-1&support=-1&text=President%20Obama%20called%20Wednesday%20on%20Congress%20to%20extend%20a%20tax%20break%20for%20students%20included%20in%20last%20year%27s%20economic%20stimulus%20package" http://spotlight.dbpedia.org/rest/annotate/

User above asked for POST request that's why I posted a POST query. I guess "content-type:application/x-www-form-urlencoded" has to be compulsorily added in a POST query.

**Comment by dav009** [comment]
:+1:
