### ISSUE TITLE
Spotting recognizes "C++" as "C Sharp (programming language)"

### ISSUE THREAD

**Issue by grivescorbett** [dbpedia-spotlight/dbpedia-spotlight#361]
Not sure if this is the correct place to put this but any time I run text through the annotate endpoint the string "C++" always gets matched to the entity C Sharp (programming language).  What might be the reason behind this / is there a way I can improve the accuracy around this term?

**Comment by tgalery** [comment]
Not entirely sure about the cause, but it could be due to a bad link from 'C++' to the C Sharp page. You can generate a new dbpedia model using the `pignlproc` repo, but if you want to modify the links around this term only, you might check out the idio model editor repo here https://github.com/idio/spotlight-model-editor
