### ISSUE TITLE
Wiki cleanup 

### ISSUE THREAD

**Issue by sandroacoelho** [dbpedia-spotlight/dbpedia-spotlight#392]
- [x]    Introduction
- [x]     Glossary
- [x]     User's manual
- [x]     Web application
- [x]     Installation
- [x]     Licenses
- [x]     FAQ
- [x]     Troubleshooting

Model backend

- [x]     Introduction
- [x]     Downloads
- [x]     Raw data
- [x]     Architecture
- [x]     Internationalization
- [x]     Web service parameters / API

Lucene backend

- [ ]     Introduction
- [ ]     Downloads
- [ ]     Architecture
- [ ]     Internationalization
- [ ]     Web service parameters / API
- [ ]     Splitting occurrences into topics

Developers

- [x]     How to join the community
- [x]     How to contribute
- [x]     Google Summer of Code - GSoC

**Comment by tgalery** [comment]
hi @sandroacoelho I'm planing to do a massive refactor of the readme as part of philipp's gsoc work, but if you want to clean up the wiki, I'd really appreciate that.

**Comment by sandroacoelho** [comment]
Hi @tgalery . Good to know :+1: 

I am planning to remove broken links, add docker support and remove references for "old formats". If you think in more improvements on the wiki that is important and I can do, just tell me.

**Comment by tgalery** [comment]
Hey @sandroacoelho That's great. I'm just wondering whether it wouldn't be best to unify the documentation in the readme, and then making references to the wiki as we see fit. There are a lot of people who open issues to ask questions because they don't bother looking at the wiki. Unifying the documentation might help in that regard, but that's only a thought. A clean up is very welcome!
