### ISSUE TITLE
400 Bad Request when annotating specific characters

### ISSUE THREAD

**Issue by wojtuch** [dbpedia-spotlight/dbpedia-spotlight#405]
Dear spotlight developers,

I noticed that when sending certain characters, the annotation fails.
I am just ignoring this in my application but I thought I will post it here since I haven't found a similar issue.

E.g. the following text causes the annotation to fail:

```
The name of Carthage,  Latin: Carthago or Karthago, Ancient Greek: Καρχηδών Karkhēdōn, Etruscan: *Carθaza, is derived from the Phoenician 𐤒𐤓𐤕 𐤇𐤃𐤔𐤕 Qart-ḥadašt meaning \"New City\" (Aramaic: קרת חדתה‎ Qeret Ḥdatha; Hebrew: קרת חדשה‎ Qeret Ḥadašah), implying it was a 'new Tyre'.
```

Best,
wojtuch

**Comment by krzd** [comment]
This seems because the conversion of the output XML to JSON fails. It returns the output just fine if you request it as XML instead.
Unfortunately that XML is not parseable, which is why the conversion fails in the first place. This is due to decoding issues on the 'Annotation' tag that contains the original text, as the one in your example above.
A simple fix I found, is to request the XML but then to simply remove the second and last line before parsing it. This seems to work, albeit a bit hacky.

**Comment by sandroacoelho** [comment]
Hi @krzd. Thanks to answer it to us
