### ISSUE TITLE
Question: /rest/annotate endpoint queries local or dbpedia servers?

### ISSUE THREAD

**Issue by mayank-chutani** [dbpedia-spotlight/dbpedia-spotlight#406]
Hi @sandroacoelho 

I wanted to know if this image downloads dbpedia data and queries are made on the localhost or the endpoint **/rest/annotate** is making requests to dbpedia servers in the backend?

If it uses dbpedia's server endpoint, how can I host it locally?

**Comment by sandroacoelho** [comment]
Hi @mayank-chutani ,

Our image uses just local data. 

Best

**Comment by mayank-chutani** [comment]
Hi @sandroacoelho 

Okay Thanks. But the response in the local instance is a bit slow. Any leads to make it faster? 
I had this confusion as I was expecting a faster response in the local machine.

**Comment by mayank-chutani** [comment]
@sandroacoelho I'm using spotlight-docker. Just FYI.

**Comment by sandroacoelho** [comment]
Hi @mayank-chutani ,

I need to check if Docker is using the same  JRE  parameters that our live instance.  I will let you know about

Best,

**Comment by sandroacoelho** [comment]
Hi @mayank-chutani ,

After a long time, I have adjusted our docker image with our demo instance parameters (also upgraded to JRE 1.7)

I am not sure that these changes will be a solution to this issue because we are running codes using a VM(Java) inside a VM (Docker  container).  We expect that the speedup will not the same as if we run it using just VM directly into the host.

Have you build an stress test? If yes, could you please repeat it with this new configuration?

Thanks,
