### ISSUE TITLE
dbpedia.org/downloads doesn't exist anymore

### ISSUE THREAD

**Issue by MerelSteenbrink** [dbpedia-spotlight/dbpedia-spotlight#426]
Hello,
When I'm trying to  run DBpedia Spotlight in my own server by using a pre-packaged JAR, I run into a problem: 
When I try to upgrade the Lucene models, the files don't exist. 
Is there an other place I can find these files?

The require files are:

- context-index-compact.tgz
- surface_forms-Wikipedia-TitRedDis.uriThresh75.tsv.spotterDictionary.gz

**Comment by tomscott1** [comment]
+1

**Comment by sandroacoelho** [comment]
Hi @MerelSteenbrink , @tomscott1 

You have two options

1  - Use Model approach
```
wget http://model.dbpedia-spotlight.org/dbpedia-spotlight-latest.jar
wget http://model.dbpedia-spotlight.org/latest_models/en.tar.gz
tar xzf en.tar.gz
java -jar dbpedia-spotlight-latest.jar en http://localhost:2222/rest
```

2 - Wait 3(three) days more

We have prepared the following repositories  to generate our Spotlight models:

 Lucene - https://github.com/dbpedia-spotlight/lucene-quickstarter

 Model  - https://github.com/dbpedia-spotlight/model-quickstarter 

Now,  we are working on the final configurations to make the monthly dumps available. You are lucky because my deadline is next Friday (March 10th). Stay tuned here, on our web-site or our Twitter account (@DBpedia)

Best,

**Comment by tomscott1** [comment]
cheers

**Comment by MerelSteenbrink** [comment]
Option one worked for me, thanks.

**Comment by sandroacoelho** [comment]
Thank you @MerelSteenbrink 

Best,
