### ISSUE TITLE
Less verbose logs

### ISSUE THREAD

**Issue by rushilagr** [dbpedia-spotlight/dbpedia-spotlight#453]
Is there any options to have the logs be less verbose?

I am asking this for two reasons - 

1.  The logs are filling up my logging system
2. They are being identified as Error or Warning level logs. Even through they are logged at info level, this what my logging system is identifying them as. Not sure if this is an issue with logging system itself.

**Comment by Skunnyk** [comment]
Yes, that's a known problem when you want to run spotlight in production. 
I tried to lower the log level based on #391 , but it does not work anymore as spotlight 1.0.0 now use slf4j (see https://github.com/dbpedia-spotlight/dbpedia-spotlight-model/commit/99065e93ee2340a4c37754ee83f83727defa136c ). 

It need to be updated to slf4j 1.7.x to allow a command line configuration, for example -Dorg.slf4j.simpleLogger.defaultLogLevel=warn to only display warn logs. But then you don't have any usefull logs anymore because almost all logs in source code  are in info level…

I have a local branch with an updated slf4j, with some info log set to error or debug, and it's a little bit better. If people are interested, I can make a PR.

**Comment by rushilagr** [comment]
Hey Skunnyk,
If possible, do make a PR. It would be of great help to me :)

Thanks a ton.

**Comment by Skunnyk** [comment]
You can look at https://github.com/Skunnyk/dbpedia-spotlight-model/tree/logs_revamp , now the server is really (too?) quiet :)
I think it's better to put a reverse proxy behind spotlight (nginx or whatever) to log all http requests.

You can start it with -Dorg.slf4j.simpleLogger.defaultLogLevel=debug if you want to see all logs.
